# Generated by Django 4.0.3 on 2022-07-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
