# Generated by Django 4.0.3 on 2022-08-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_sub_title_note_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='subTitle',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
