# Generated by Django 4.0.3 on 2022-08-18 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_note_category_alter_note_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
