# Generated by Django 4.0.3 on 2022-08-18 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_note_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
